apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2018-09-13T08:19:49Z'
  generation: 2
  labels:
    app: springboot-server
  name: springboot-server
  namespace: test
  resourceVersion: ''
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/test/deploymentconfigs/springboot-server
  uid: 
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: springboot-server
    deploymentconfig: springboot-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: springboot-server
        deploymentconfig: springboot-server
    spec:
      containers:
        - image: 'registry.yk.com/test/devopstest02:1.1'
          imagePullPolicy: Always
          name: springboot-server
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: springboot-server-volume-1
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: springboot-server-volume-1
  test: false
  triggers:
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-09-13T08:19:56Z'
      lastUpdateTime: '2018-09-13T08:19:56Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2018-09-13T08:19:53Z'
      lastUpdateTime: '2018-09-13T08:19:56Z'
      message: >-
        replication controller "springboot-server-1" successfully rolled
        out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
